/*
Copyright The cert-manager Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by controller-gen. DO NOT EDIT.

package v1alpha2

import (
	v1 "k8s.io/api/core/v1"
)

// KeyValueTargetApplyConfiguration represents a declarative configuration of the KeyValueTarget type for use
// with apply.
//
// KeyValueTarget is the specification of key value target resources as ConfigMaps and Secrets.
type KeyValueTargetApplyConfiguration struct {
	// data is the specification of the object's `data` field.
	Data []TargetKeyValueApplyConfiguration `json:"data,omitempty"`
	// metadata is an optional set of labels and annotations to be copied to the target.
	Metadata *TargetMetadataApplyConfiguration `json:"metadata,omitempty"`
	// type is the type of the target Secret. Only applicable when the target is a Secret.
	// If not set, defaults to Opaque.
	Type *v1.SecretType `json:"type,omitempty"`
}

// KeyValueTargetApplyConfiguration constructs a declarative configuration of the KeyValueTarget type for use with
// apply.
func KeyValueTarget() *KeyValueTargetApplyConfiguration {
	return &KeyValueTargetApplyConfiguration{}
}

// WithData adds the given value to the Data field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Data field.
func (b *KeyValueTargetApplyConfiguration) WithData(values ...*TargetKeyValueApplyConfiguration) *KeyValueTargetApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithData")
		}
		b.Data = append(b.Data, *values[i])
	}
	return b
}

// WithMetadata sets the Metadata field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Metadata field is set to the value of the last call.
func (b *KeyValueTargetApplyConfiguration) WithMetadata(value *TargetMetadataApplyConfiguration) *KeyValueTargetApplyConfiguration {
	b.Metadata = value
	return b
}

// WithType sets the Type field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Type field is set to the value of the last call.
func (b *KeyValueTargetApplyConfiguration) WithType(value v1.SecretType) *KeyValueTargetApplyConfiguration {
	b.Type = &value
	return b
}
